### ISSUE TITLE
Ad Account or Campaign Dropdown has no data

### ISSUE THREAD

**Issue by PrimacyAgency** [hellowearemito/dataconnector-facebook#1]
I am trying to make a connection to our Facebook account and have successful authorized the connector -- however the drop down arrow for specifying the Ad Account to use does not present any accounts.  Using latest Chrome Mac browser

**Comment by djozsef** [comment]
Hello @PrimacyAgency,

Your user who wants to fetch data needs to have read rights granted in Facebook Business Manager. The connector fetches available Ad Accounts from the businesses you are assigned to in Business Manager.

Please check if your user is assigned to at least one business.
