### ISSUE TITLE
Can't Connect URL

### ISSUE THREAD

**Issue by gjdaily** [hellowearemito/dataconnector-facebook#10]
Hello,

Every time I try to authorize Facebook, I get an error. 

<img width="581" alt="screen shot 2018-02-08 at 2 35 26 pm" src="https://user-images.githubusercontent.com/36281302/35999523-5e5456a0-0cdd-11e8-854a-cbe666b08d78.png">

Please advise.

Thank you,

**Comment by PInger69** [comment]
Me too. Same issue as gjdaily. Any resolution? Thanks!

**Comment by StuLimeSmith** [comment]
Exact same issue here. :-)

**Comment by djozsef** [comment]
Hello @gjdaily @PInger69 @StuLimeSmith,

Please re-check. We had to update our Community App's redirect URI's as Facebook restrictions became effective. In some cases it is needed to remove and re-authorize the app. To remove app authorization navigate to Facebook > Settings page > Apps and remove "Community Data Connector" from the "Logged in with Facebook" section. Then re-authorize the connector in Data Studio.

Please ping back if it solved your problem. Thanks :)
