### ISSUE TITLE
Facebook Ad Account missing in connector

### ISSUE THREAD

**Issue by tahopetis** [hellowearemito/dataconnector-facebook#13]
Hi,
Could you please help me resolving this issue? I saw the thread earlier and I tried the url 

https://graph.facebook.com/v2.10/me/adaccounts?fields=business_name&access_token=%3CACCESS_TOKEN%3E

this is the result

{
   "error": {
      "message": "Invalid OAuth access token.",
      "type": "OAuthException",
      "code": 190,
      "fbtrace_id": "BaWg33f65xE"
   }
}

**Comment by djozsef** [comment]
Hello @tahopetis,

you need to substitute '<ACCESS_TOKEN>' with your valid access token.

**Comment by djozsef** [comment]
Closed due to inactivity.
