### ISSUE TITLE
no accounts

### ISSUE THREAD

**Issue by toqueboy13** [hellowearemito/dataconnector-facebook#14]
hi there. i've tried logging in with two different accounts that have Facebook admin access and ads manager admin access  and neither are populating the connection with any information:
![image](https://user-images.githubusercontent.com/37162604/37125913-ca88fc96-222b-11e8-8c98-942d15e72234.png)

i'm not sure what i'm doing wrong. if you could help, that'd be great. thanks. the account i'm linked with now should have a personal account and then 3 different ad accounts tied to it.

**Comment by djozsef** [comment]
Hello @toqueboy13,

Could you please check what do you get when you try [this](https://github.com/hellowearemito/dataconnector-facebook/issues/3#issuecomment-335620182) API call?

**Comment by djozsef** [comment]
Closed due to inactivity.

**Comment by SimpleSimpleAds** [comment]
I am looking into the connector issue for toqueboy13. The response from the api call is the following.

I used the Graph API Explorer application to get these results with ads_read permissions. I am not sure how to do this using your facebook application.

I have replaced the actual business account numbers with act_xxxxxxxxxxxxxxx

`{
   "data": [
      {
         "business_name": "",
         "id": "act_xxxxxxxxxxxxxxx"
      },
      {
         "business_name": "",
         "id": "act_xxxxxxxxxxxxxxx"
      },
      {
         "business_name": "",
         "id": "act_xxxxxxxxxxxxxxx"
      },
      {
         "business_name": "",
         "id": "act_xxxxxxxxxxxxxxx"
      }
   ],
   "paging": {
      "cursors": {
         "before": "NjAwMzA1ODEyODkyMQZDZD",
         "after": "NjA0OTc2ODc3Mjg1MAZDZD"
      }
   }
}`
