### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by fedega75** [hellowearemito/dataconnector-facebook#15]
Hello
suddenly the connection plugin stopped working.

**Error details
An error occurred while requesting data returned from the community connector. If the problem persists, report it to the community connector vendor.
Error ID: ac70405c**

all permissions are correctly active
Does anyone have any suggestions?
Thanks

**Comment by djozsef** [comment]
Hello @fedega75,

Thanks for reporting, others have experienced very same issues. We are debugging the problem, you can follow the progress under #12

**Comment by djozsef** [comment]
Duplicate of #12
