### ISSUE TITLE
Incomplete Authorization for Native Facebook Connector 

### ISSUE THREAD

**Issue by princeewill** [hellowearemito/dataconnector-facebook#16]
After i authorized the Native Facebook Connector to have access to my Facebook account, it told me the process has been successfully completed so i can close the window. 
I did that but afterwards the app still isn't authorized

**Comment by djozsef** [comment]
Hello @princeewill, 

We have released a new version of the the Connector that fixes this issue. Please try to re-add it as a new data source.
