### ISSUE TITLE
Issue connecting the data source

### ISSUE THREAD

**Issue by JhonniT** [hellowearemito/dataconnector-facebook#23]
I authorized the connector at Google and Facebook, but after the Facebook popup i can't get the datasource to be set up the authorisation for facebook keeps being blue meaning not authorized. is there a work around or am i just not doing it right? 

Looking forward to an answer. Many thanks in advance

**Comment by djozsef** [comment]
Hello @JhonniT,

It must be related to #22. Please re-auth and try again.
