### ISSUE TITLE
reset authorization

### ISSUE THREAD

**Issue by scalefox** [hellowearemito/dataconnector-facebook#34]
Hey, I was trying to setup up with own fb app. This did not work because some domain was missing within the app settings. Can you please tell me what this needed domain is? Second problem I experience is, that I am unable to get back to the step where I can choose to use your app or go with an own one. I deleted the FB App I was initially testing with and now after clicking "Authorize" I am just redirected to FB and of course it tells me the app does not exist. Can you please help?

**Comment by roelvdkrabben** [comment]
Got exactly the same problem. Any heads up on this one yet?

**Comment by scalefox** [comment]
> Got exactly the same problem. Any heads up on this one yet?

I chose to go with supermetrics for google sheets. The better solution on the long run.
