### ISSUE TITLE
Stuck in authorization loop

### ISSUE THREAD

**Issue by motiveunknown** [hellowearemito/dataconnector-facebook#7]
Hi, I have authorised Data Studio requires to use this community connector, but when trying the second step to authorize Native Facebook Connector to connect to data I approve the popup but I keep being taken back to the setup page without the authorization being processed.

**Comment by PatrycjaF** [comment]
Hi, I've got the same problem. It won't let me pass through the authorization stage. Anybody help?

**Comment by StephanieErne** [comment]
I've also got the same issue when trying to authorize the connector.

**Comment by jonathan-vieira** [comment]
i'm stuck here too

**Comment by djozsef** [comment]
Hello @motiveunknown @PatrycjaF @StephanieErne @jonathan-vieira,

Please refer to the following solutions:

- https://github.com/hellowearemito/dataconnector-facebook/issues/4#issuecomment-335622067
- https://github.com/hellowearemito/dataconnector-facebook/issues/4#issuecomment-335629555
